displayName=Prayer Reminder
author=1Defence
description=Reminds you quick prayer is no longer on.
tags=prayer,alting,hopping,quick
version=
plugins=com.prayerreminder.PrayerReminderPlugin
build=standard